<html>
<head>
    <meta charset="utf-8"/>
<meta name="description" content="负重前行，O52O加油吧少年"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>

<title>JavaScript 教程-语法专题-错误处理机制 | O52O</title>

<link rel="shortcut icon" href="https://0520.eu.org/favicon.ico?v=1731204974435">

<link href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://0520.eu.org/styles/main.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css">

<script src="https://cdn.jsdelivr.net/npm/@highlightjs/cdn-assets/highlight.min.js"></script>
<script src="https://cdn.bootcss.com/highlight.js/9.15.10/languages/dockerfile.min.js"></script>
<script src="https://cdn.bootcss.com/highlight.js/9.15.10/languages/dart.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/moment@2.27.0/moment.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.min.js"></script>
<!-- DEMO JS -->
<!--<script src="media/scripts/index.js"></script>-->



    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.css">
</head>
<body>
<div class="main gt-bg-theme-color-first">
    <nav class="navbar navbar-expand-lg">
    <div class="navbar-brand">
        <img class="user-avatar" src="/images/avatar.png" alt="头像">
        <div class="site-name gt-c-content-color-first">
            O52O
        </div>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-bars gt-c-content-color-first" style="font-size: 18px"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="navbar-nav mr-auto" style="text-align: center">
            
                <div class="nav-item">
                    
                        <a href="/" class="menu gt-a-link">
                            首页
                        </a>
                    
                </div>
            
                <div class="nav-item">
                    
                        <a href="/post/javascript" class="menu gt-a-link">
                            Javascript
                        </a>
                    
                </div>
            
                <div class="nav-item">
                    
                        <a href="/archives" class="menu gt-a-link">
                            归档
                        </a>
                    
                </div>
            
                <div class="nav-item">
                    
                        <a href="/tags" class="menu gt-a-link">
                            标签
                        </a>
                    
                </div>
            
                <div class="nav-item">
                    
                        <a href="/friends" class="menu gt-a-link">
                            友链
                        </a>
                    
                </div>
            
                <div class="nav-item">
                    
                        <a href="/post/about" class="menu gt-a-link">
                            关于
                        </a>
                    
                </div>
            
        </div>
        <div style="text-align: center">
            <form id="gridea-search-form" style="position: relative" data-update="1731204974435" action="/search/index.html">
                <input class="search-input" autocomplete="off" spellcheck="false" name="q" placeholder="搜索文章" />
                <i class="fas fa-search gt-c-content-color-first" style="position: absolute; top: 9px; left: 10px;"></i>
            </form>
        </div>
    </div>
</nav>

    <div class="post-container">
        <div class="post-detail gt-bg-theme-color-second">
            <article class="gt-post-content">
                <h2 class="post-title">
                    JavaScript 教程-语法专题-错误处理机制
                </h2>
                <div class="post-info">
                    <time class="post-time gt-c-content-color-first">
                        · 2024-05-31 ·
                    </time>
                    
                        <a href="https://0520.eu.org/tag/G-9IdbXM1/" class="post-tags">
                            # JavaScript 教程
                        </a>
                    
                </div>
                <div class="post-content">
                    <p><ul class="markdownIt-TOC">
<li><a href="#%E9%94%99%E8%AF%AF%E5%A4%84%E7%90%86%E6%9C%BA%E5%88%B6">错误处理机制</a>
<ul>
<li><a href="#error-%E5%AE%9E%E4%BE%8B%E5%AF%B9%E8%B1%A1">Error 实例对象</a></li>
<li><a href="#%E5%8E%9F%E7%94%9F%E9%94%99%E8%AF%AF%E7%B1%BB%E5%9E%8B">原生错误类型</a>
<ul>
<li><a href="#syntaxerror-%E5%AF%B9%E8%B1%A1">SyntaxError 对象</a></li>
<li><a href="#referenceerror-%E5%AF%B9%E8%B1%A1">ReferenceError 对象</a></li>
<li><a href="#rangeerror-%E5%AF%B9%E8%B1%A1">RangeError 对象</a></li>
<li><a href="#typeerror-%E5%AF%B9%E8%B1%A1">TypeError 对象</a></li>
<li><a href="#urierror-%E5%AF%B9%E8%B1%A1">URIError 对象</a></li>
<li><a href="#evalerror-%E5%AF%B9%E8%B1%A1">EvalError 对象</a></li>
<li><a href="#%E6%80%BB%E7%BB%93">总结</a></li>
</ul>
</li>
<li><a href="#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%94%99%E8%AF%AF">自定义错误</a></li>
<li><a href="#throw-%E8%AF%AD%E5%8F%A5">throw 语句</a></li>
<li><a href="#trycatch-%E7%BB%93%E6%9E%84">try...catch 结构</a></li>
<li><a href="#finally-%E4%BB%A3%E7%A0%81%E5%9D%97">finally 代码块</a></li>
<li><a href="#%E5%8F%82%E8%80%83%E8%BF%9E%E6%8E%A5">参考连接</a></li>
</ul>
</li>
</ul>
</p>
<h1 id="错误处理机制">错误处理机制</h1>
<h2 id="error-实例对象">Error 实例对象</h2>
<p>JavaScript 解析或运行时，一旦发生错误，引擎就会抛出一个错误对象。JavaScript 原生提供<code>Error</code>构造函数，所有抛出的错误都是这个构造函数的实例。</p>
<pre><code class="language-javascript">var err = new Error('出错了');
err.message // &quot;出错了&quot;
</code></pre>
<!-- more -->
<p>上面代码中，我们调用<code>Error()</code>构造函数，生成一个实例对象<code>err</code>。<code>Error()</code>构造函数接受一个参数，表示错误提示，可以从实例的<code>message</code>属性读到这个参数。抛出<code>Error</code>实例对象以后，整个程序就中断在发生错误的地方，不再往下执行。</p>
<p>JavaScript 语言标准只提到，<code>Error</code>实例对象必须有<code>message</code>属性，表示出错时的提示信息，没有提到其他属性。大多数 JavaScript 引擎，对<code>Error</code>实例还提供<code>name</code>和<code>stack</code>属性，分别表示错误的名称和错误的堆栈，但它们是非标准的，不是每种实现都有。</p>
<ul>
<li><strong>message</strong>：错误提示信息</li>
<li><strong>name</strong>：错误名称（非标准属性）</li>
<li><strong>stack</strong>：错误的堆栈（非标准属性）</li>
</ul>
<p>使用<code>name</code>和<code>message</code>这两个属性，可以对发生什么错误有一个大概的了解。</p>
<pre><code class="language-javascript">if (error.name) {
  console.log(error.name + ': ' + error.message);
}
</code></pre>
<p><code>stack</code>属性用来查看错误发生时的堆栈。</p>
<pre><code class="language-javascript">function throwit() {
  throw new Error('');
}

function catchit() {
  try {
    throwit();
  } catch(e) {
    console.log(e.stack); // print stack trace
  }
}

catchit()
// Error
//    at throwit (~/examples/throwcatch.js:9:11)
//    at catchit (~/examples/throwcatch.js:3:9)
//    at repl:1:5
</code></pre>
<p>上面代码中，错误堆栈的最内层是<code>throwit</code>函数，然后是<code>catchit</code>函数，最后是函数的运行环境。</p>
<h2 id="原生错误类型">原生错误类型</h2>
<p><code>Error</code>实例对象是最一般的错误类型，在它的基础上，JavaScript 还定义了其他6种错误对象。也就是说，存在<code>Error</code>的6个派生对象。</p>
<h3 id="syntaxerror-对象">SyntaxError 对象</h3>
<p><code>SyntaxError</code>对象是解析代码时发生的语法错误。</p>
<pre><code class="language-javascript">// 变量名错误
var 1a;
// Uncaught SyntaxError: Invalid or unexpected token

// 缺少括号
console.log 'hello');
// Uncaught SyntaxError: Unexpected string
</code></pre>
<p>上面代码的错误，都是在语法解析阶段就可以发现，所以会抛出<code>SyntaxError</code>。第一个错误提示是“token 非法”，第二个错误提示是“字符串不符合要求”。</p>
<h3 id="referenceerror-对象">ReferenceError 对象</h3>
<p><code>ReferenceError</code>对象是引用一个不存在的变量时发生的错误。</p>
<pre><code class="language-javascript">// 使用一个不存在的变量
unknownVariable
// Uncaught ReferenceError: unknownVariable is not defined
</code></pre>
<p>另一种触发场景是，将一个值分配给无法分配的对象，比如对函数的运行结果赋值。</p>
<pre><code class="language-javascript">// 等号左侧不是变量
console.log() = 1
// Uncaught ReferenceError: Invalid left-hand side in assignment
</code></pre>
<p>上面代码对函数<code>console.log</code>的运行结果赋值，结果引发了<code>ReferenceError</code>错误。</p>
<h3 id="rangeerror-对象">RangeError 对象</h3>
<p><code>RangeError</code>对象是一个值超出有效范围时发生的错误。主要有几种情况，一是数组长度为负数，二是<code>Number</code>对象的方法参数超出范围，以及函数堆栈超过最大值。</p>
<pre><code class="language-javascript">// 数组长度不得为负数
new Array(-1)
// Uncaught RangeError: Invalid array length
</code></pre>
<h3 id="typeerror-对象">TypeError 对象</h3>
<p><code>TypeError</code>对象是变量或参数不是预期类型时发生的错误。比如，对字符串、布尔值、数值等原始类型的值使用<code>new</code>命令，就会抛出这种错误，因为<code>new</code>命令的参数应该是一个构造函数。</p>
<pre><code class="language-javascript">new 123
// Uncaught TypeError: 123 is not a constructor

var obj = {};
obj.unknownMethod()
// Uncaught TypeError: obj.unknownMethod is not a function
</code></pre>
<p>上面代码的第二种情况，调用对象不存在的方法，也会抛出<code>TypeError</code>错误，因为<code>obj.unknownMethod</code>的值是<code>undefined</code>，而不是一个函数。</p>
<h3 id="urierror-对象">URIError 对象</h3>
<p><code>URIError</code>对象是 URI 相关函数的参数不正确时抛出的错误，主要涉及<code>encodeURI()</code>、<code>decodeURI()</code>、<code>encodeURIComponent()</code>、<code>decodeURIComponent()</code>、<code>escape()</code>和<code>unescape()</code>这六个函数。</p>
<pre><code class="language-javascript">decodeURI('%2')
// URIError: URI malformed
</code></pre>
<h3 id="evalerror-对象">EvalError 对象</h3>
<p><code>eval</code>函数没有被正确执行时，会抛出<code>EvalError</code>错误。该错误类型已经不再使用了，只是为了保证与以前代码兼容，才继续保留。</p>
<h3 id="总结">总结</h3>
<p>以上这6种派生错误，连同原始的<code>Error</code>对象，都是构造函数。开发者可以使用它们，手动生成错误对象的实例。这些构造函数都接受一个参数，代表错误提示信息（message）。</p>
<pre><code class="language-javascript">var err1 = new Error('出错了！');
var err2 = new RangeError('出错了，变量超出有效范围！');
var err3 = new TypeError('出错了，变量类型无效！');

err1.message // &quot;出错了！&quot;
err2.message // &quot;出错了，变量超出有效范围！&quot;
err3.message // &quot;出错了，变量类型无效！&quot;
</code></pre>
<h2 id="自定义错误">自定义错误</h2>
<p>除了 JavaScript 原生提供的七种错误对象，还可以定义自己的错误对象。</p>
<pre><code class="language-javascript">function UserError(message) {
  this.message = message || '默认信息';
  this.name = 'UserError';
}

UserError.prototype = new Error();
UserError.prototype.constructor = UserError;
</code></pre>
<p>上面代码自定义一个错误对象<code>UserError</code>，让它继承<code>Error</code>对象。然后，就可以生成这种自定义类型的错误了。</p>
<pre><code class="language-javascript">new UserError('这是自定义的错误！');
</code></pre>
<h2 id="throw-语句">throw 语句</h2>
<p><code>throw</code>语句的作用是手动中断程序执行，抛出一个错误。</p>
<pre><code class="language-javascript">var x = -1;

if (x &lt;= 0) {
  throw new Error('x 必须为正数');
}
// Uncaught Error: x 必须为正数
</code></pre>
<p>上面代码中，如果变量<code>x</code>小于等于<code>0</code>，就手动抛出一个错误，告诉用户<code>x</code>的值不正确，整个程序就会在这里中断执行。可以看到，<code>throw</code>抛出的错误就是它的参数，这里是一个<code>Error</code>对象的实例。</p>
<p><code>throw</code>也可以抛出自定义错误。</p>
<pre><code class="language-javascript">function UserError(message) {
  this.message = message || '默认信息';
  this.name = 'UserError';
}

throw new UserError('出错了！');
// Uncaught UserError {message: &quot;出错了！&quot;, name: &quot;UserError&quot;}
</code></pre>
<p>上面代码中，<code>throw</code>抛出的是一个<code>UserError</code>实例。</p>
<p>实际上，<code>throw</code>可以抛出任何类型的值。也就是说，它的参数可以是任何值。</p>
<pre><code class="language-javascript">// 抛出一个字符串
throw 'Error！';
// Uncaught Error！

// 抛出一个数值
throw 42;
// Uncaught 42

// 抛出一个布尔值
throw true;
// Uncaught true

// 抛出一个对象
throw {
  toString: function () {
    return 'Error!';
  }
};
// Uncaught {toString: ƒ}
</code></pre>
<p>对于 JavaScript 引擎来说，遇到<code>throw</code>语句，程序就中止了。引擎会接收到<code>throw</code>抛出的信息，可能是一个错误实例，也可能是其他类型的值。</p>
<h2 id="trycatch-结构">try...catch 结构</h2>
<p>一旦发生错误，程序就中止执行了。JavaScript 提供了<code>try...catch</code>结构，允许对错误进行处理，选择是否往下执行。</p>
<pre><code class="language-javascript">try {
  throw new Error('出错了!');
} catch (e) {
  console.log(e.name + &quot;: &quot; + e.message);
  console.log(e.stack);
}
// Error: 出错了!
//   at &lt;anonymous&gt;:3:9
//   ...
</code></pre>
<p>上面代码中，<code>try</code>代码块抛出错误（上例用的是<code>throw</code>语句），JavaScript 引擎就立即把代码的执行，转到<code>catch</code>代码块，或者说错误被<code>catch</code>代码块捕获了。<code>catch</code>接受一个参数，表示<code>try</code>代码块抛出的值。</p>
<p>如果你不确定某些代码是否会报错，就可以把它们放在<code>try...catch</code>代码块之中，便于进一步对错误进行处理。</p>
<pre><code class="language-javascript">try {
  f();
} catch(e) {
  // 处理错误
}
</code></pre>
<p>上面代码中，如果函数<code>f</code>执行报错，就会进行<code>catch</code>代码块，接着对错误进行处理。</p>
<p><code>catch</code>代码块捕获错误之后，程序不会中断，会按照正常流程继续执行下去。</p>
<pre><code class="language-javascript">try {
  throw &quot;出错了&quot;;
} catch (e) {
  console.log(111);
}
console.log(222);
// 111
// 222
</code></pre>
<p>上面代码中，<code>try</code>代码块抛出的错误，被<code>catch</code>代码块捕获后，程序会继续向下执行。</p>
<p><code>catch</code>代码块之中，还可以再抛出错误，甚至使用嵌套的<code>try...catch</code>结构。</p>
<pre><code class="language-javascript">var n = 100;

try {
  throw n;
} catch (e) {
  if (e &lt;= 50) {
    // ...
  } else {
    throw e;
  }
}
// Uncaught 100
</code></pre>
<p>上面代码中，<code>catch</code>代码之中又抛出了一个错误。</p>
<p>为了捕捉不同类型的错误，<code>catch</code>代码块之中可以加入判断语句。</p>
<pre><code class="language-javascript">try {
  foo.bar();
} catch (e) {
  if (e instanceof EvalError) {
    console.log(e.name + &quot;: &quot; + e.message);
  } else if (e instanceof RangeError) {
    console.log(e.name + &quot;: &quot; + e.message);
  }
  // ...
}
</code></pre>
<p>上面代码中，<code>catch</code>捕获错误之后，会判断错误类型（<code>EvalError</code>还是<code>RangeError</code>），进行不同的处理。</p>
<h2 id="finally-代码块">finally 代码块</h2>
<p><code>try...catch</code>结构允许在最后添加一个<code>finally</code>代码块，表示不管是否出现错误，都必需在最后运行的语句。</p>
<pre><code class="language-javascript">function cleansUp() {
  try {
    throw new Error('出错了……');
    console.log('此行不会执行');
  } finally {
    console.log('完成清理工作');
  }
}

cleansUp()
// 完成清理工作
// Uncaught Error: 出错了……
//    at cleansUp (&lt;anonymous&gt;:3:11)
//    at &lt;anonymous&gt;:10:1
</code></pre>
<p>上面代码中，由于没有<code>catch</code>语句块，一旦发生错误，代码就会中断执行。中断执行之前，会先执行<code>finally</code>代码块，然后再向用户提示报错信息。</p>
<pre><code class="language-javascript">function idle(x) {
  try {
    console.log(x);
    return 'result';
  } finally {
    console.log('FINALLY');
  }
}

idle('hello')
// hello
// FINALLY
</code></pre>
<p>上面代码中，<code>try</code>代码块没有发生错误，而且里面还包括<code>return</code>语句，但是<code>finally</code>代码块依然会执行。而且，这个函数的返回值还是<code>result</code>。</p>
<p>下面的例子说明，<code>return</code>语句的执行是排在<code>finally</code>代码之前，只是等<code>finally</code>代码执行完毕后才返回。</p>
<pre><code class="language-javascript">var count = 0;
function countUp() {
  try {
    return count;
  } finally {
    count++;
  }
}

countUp()
// 0
count
// 1
</code></pre>
<p>上面代码说明，<code>return</code>语句里面的<code>count</code>的值，是在<code>finally</code>代码块运行之前就获取了。</p>
<p>下面是<code>finally</code>代码块用法的典型场景。</p>
<pre><code class="language-javascript">openFile();

try {
  writeFile(Data);
} catch(e) {
  handleError(e);
} finally {
  closeFile();
}
</code></pre>
<p>上面代码首先打开一个文件，然后在<code>try</code>代码块中写入文件，如果没有发生错误，则运行<code>finally</code>代码块关闭文件；一旦发生错误，则先使用<code>catch</code>代码块处理错误，再使用<code>finally</code>代码块关闭文件。</p>
<p>下面的例子充分反映了<code>try...catch...finally</code>这三者之间的执行顺序。</p>
<pre><code class="language-javascript">function f() {
  try {
    console.log(0);
    throw 'bug';
  } catch(e) {
    console.log(1);
    return true; // 这句原本会延迟到 finally 代码块结束再执行
    console.log(2); // 不会运行
  } finally {
    console.log(3);
    return false; // 这句会覆盖掉前面那句 return
    console.log(4); // 不会运行
  }

  console.log(5); // 不会运行
}

var result = f();
// 0
// 1
// 3

result
// false
</code></pre>
<p>上面代码中，<code>catch</code>代码块结束执行之前，会先执行<code>finally</code>代码块。</p>
<p><code>catch</code>代码块之中，触发转入<code>finally</code>代码块的标志，不仅有<code>return</code>语句，还有<code>throw</code>语句。</p>
<pre><code class="language-javascript">function f() {
  try {
    throw '出错了！';
  } catch(e) {
    console.log('捕捉到内部错误');
    throw e; // 这句原本会等到finally结束再执行
  } finally {
    return false; // 直接返回
  }
}

try {
  f();
} catch(e) {
  // 此处不会执行
  console.log('caught outer &quot;bogus&quot;');
}

//  捕捉到内部错误
</code></pre>
<p>上面代码中，进入<code>catch</code>代码块之后，一遇到<code>throw</code>语句，就会去执行<code>finally</code>代码块，其中有<code>return false</code>语句，因此就直接返回了，不再会回去执行<code>catch</code>代码块剩下的部分了。</p>
<p><code>try</code>代码块内部，还可以再使用<code>try</code>代码块。</p>
<pre><code class="language-javascript">try {
  try {
    consle.log('Hello world!'); // 报错
  }
  finally {
    console.log('Finally');
  }
  console.log('Will I run?');
} catch(error) {
  console.error(error.message);
}
// Finally
// consle is not defined
</code></pre>
<p>上面代码中，<code>try</code>里面还有一个<code>try</code>。内层的<code>try</code>报错（<code>console</code>拼错了），这时会执行内层的<code>finally</code>代码块，然后抛出错误，被外层的<code>catch</code>捕获。</p>
<h2 id="参考连接">参考连接</h2>
<ul>
<li>Jani Hartikainen, <a href="http://davidwalsh.name/fix-javascript-errors">JavaScript Errors and How to Fix Them</a></li>
</ul>

                </div>
            </article>
        </div>

        
            <div class="next-post">
                <div class="next gt-c-content-color-first">下一篇</div>
                <a href="https://0520.eu.org/post/javascript-features-conversion/" class="post-title gt-a-link">
                    JavaScript 教程-语法专题-数据类型的转换
                </a>
            </div>
        

        

        
            

            
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/disqusjs/dist/disqusjs.css">
<script src="https://cdn.jsdelivr.net/npm/disqusjs/dist/disqus.js"></script>

<div id="disqus_thread"></div>

<script>

var options = {
  shortname: '0520',
  apikey: '',
}
if ('https://0520.disqus.com') {
  options.api = 'https://0520.disqus.com'
}
var dsqjs = new DisqusJS(options)

</script>

            
        

        

        <div class="site-footer gt-c-content-color-first">
    <div class="slogan gt-c-content-color-first"></div>
    <div class="social-container">
        
            
                <a href="https://github.com/lovoupw" target="_blank">
                    <i class="fab fa-github gt-c-content-color-first"></i>
                </a>
            
        
            
                <a href="https://twitter.com/lovou_pw" target="_blank">
                    <i class="fab fa-twitter gt-c-content-color-first"></i>
                </a>
            
        
            
                <a href="https://weibo.com/316302888" target="_blank">
                    <i class="fab fa-weibo gt-c-content-color-first"></i>
                </a>
            
        
            
                <a href="https://zhihu.com/people/feng-ling-71-63-43" target="_blank">
                    <i class="fab fa-zhihu gt-c-content-color-first"></i>
                </a>
            
        
            
        
            
        
    </div>
    <div class="footer-info">
        Copyright &copy;2024 负重前行 <a href="https://blog.lovou.pw" target="_blank">O52O</a> 加油吧少年
    </div>
    <div>
        Theme by <a href="https://imhanjie.com/" target="_blank">imhanjie</a>, Powered by <a
                href="https://github.com/getgridea/gridea" target="_blank">Gridea | <a href="https://0520.eu.org/atom.xml" target="_blank">RSS</a></a>
    </div>
</div>

<script>
  hljs.initHighlightingOnLoad()
</script>

    </div>
</div>
</body>
</html>
